apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fulcimen
  name: fulcimen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fulcimen
  template:
    metadata:
      annotations:
        imageregistry: "https://docker.pkg.github.com"
      labels:
        app: fulcimen
    spec:
      containers:
        - name: fulcimen
          image: docker.pkg.github.com/mlibrary/heliotropium/fulcimen:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: github-packages-read