apiVersion: apps/v1
kind: Deployment
metadata:
  name: fulcimen-mysql
spec:
  selector:
    matchLabels:
      app: fulcimen
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fulcimen
    spec:
      containers:
        - image: mysql:5.6
          name: fulcimen-mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: fulcimen-mysql
          volumeMounts:
            - name: fulcimen-mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: fulcimen-mysql-persistent-storage
          persistentVolumeClaim:
            claimName: fulcimen-mysql-pv-claim