name: deploy-branch-to-testing

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: fulcrum-testing
    steps:
      - name: GITHUB_SHA
        run: echo "$GITHUB_SHA"
      - name: GITHUB_REF
        run: echo "$GITHUB_REF"
      - name: SECRETS
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: echo "$SECRETS"
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
      - name: Authenticate with kubernetes
        run: |
          mkdir -p ${HOME}/.kube/certs/cluster
          echo ${{ secrets.CA_CRT_BASE64 }} | base64 -d > ${HOME}/.kube/certs/cluster/k8s-ca.crt
          kubectl config set-cluster cluster --certificate-authority=${HOME}/.kube/certs/cluster/k8s-ca.crt --server=`echo ${{ secrets.SERVER_URL_BASE64 }} | base64 -d`
          kubectl config set-credentials default --token=`echo ${{ secrets.TOKEN_BASE64 }} | base64 -d`
          kubectl config set-context default --cluster=cluster --user=default --namespace=`echo ${{ secrets.NAMESPACE_BASE64 }} | base64 -d`
          kubectl config use-context default
      - name: Deploy
        run: |
          kubectl config view
          kubectl config current-context
#          kubectl set image deployment web web=docker.pkg.github.com/mlibrary/patron_account/patron_account:${{ steps.tag_check.outputs.tag }}