name: package-branch-image

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: craftech-io/package-action@v3.1.0
        name: Package
        id: url-GPR
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          image_name: fulcimen
          tags: |
            latest
            ${{ github.sha }}
      - name: imageURL
        run: echo ${{ steps.url-GPR.outputs.imageURL }}